name: Go

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  MYSQL_TEST_USER: gotest
  MYSQL_TEST_PASS: secret
  MYSQL_TEST_ADDR: 127.0.0.1:3306

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        go:
          - "1.19"
          - "1.18"
        mysql:
          - "8.0"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: ${{ matrix.mysql }}
          user: ${{ env.MYSQL_TEST_USER }}
          password: ${{ env.MYSQL_TEST_PASS }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Test
        run: make test
