name: Go

on:
  push:
  pull_request:
    branches: [master]

env:
  MYSQL_TEST_USER: gotest
  MYSQL_TEST_PASS: secret
  MYSQL_TEST_ADDR: 127.0.0.1:3306

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.18"
    steps:
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          user: ${{ env.MYSQL_TEST_USER }}
          password: ${{ env.MYSQL_TEST_PASS }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Test
        run: make test
